package util;

/*
 * 내가 이동하고싶은 화면 넣기
 */
public enum View {
	HOME, MAIN, 
	MEMBER, MEMBER_SIGNUP, MEMBER_LOGIN, MEMBER_RESIGN,
	MEMBER_PRODBUY, MEMBER_PRODCHECK, MEMBER_PRODBAG,
	ADMIN, PROD_ALL, ADMIN_LOGIN, PROD_CREATE, PROD_UPDATE, PROD_DELETE
	
}
